// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: proto/ContactResolver.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_ContactResolver_proto protoreflect.FileDescriptor

var file_proto_ContactResolver_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x83, 0x02, 0x0a,
	0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72,
	0x12, 0x45, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x49, 0x6e, 0x66,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0a, 0x41, 0x64,
	0x64, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x42, 0x45, 0x0a, 0x1f, 0x63, 0x6f, 0x6d, 0x2e, 0x6a, 0x6f, 0x78, 0x72, 0x61, 0x79,
	0x73, 0x2e, 0x67, 0x6f, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x73, 0x76, 0x72, 0x2e, 0x72, 0x65, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x72, 0x42, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x01, 0x5a, 0x0a, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var file_proto_ContactResolver_proto_goTypes = []interface{}{
	(*Empty)(nil),               // 0: protobuf.Empty
	(*String)(nil),              // 1: protobuf.String
	(*ContactInfo)(nil),         // 2: protobuf.ContactInfo
	(*ContactMetaInfoList)(nil), // 3: protobuf.ContactMetaInfoList
}
var file_proto_ContactResolver_proto_depIdxs = []int32{
	0, // 0: protobuf.ContactResolver.GetAllContactInfo:input_type -> protobuf.Empty
	1, // 1: protobuf.ContactResolver.GetContactInfo:input_type -> protobuf.String
	1, // 2: protobuf.ContactResolver.DeleteContact:input_type -> protobuf.String
	2, // 3: protobuf.ContactResolver.AddContact:input_type -> protobuf.ContactInfo
	3, // 4: protobuf.ContactResolver.GetAllContactInfo:output_type -> protobuf.ContactMetaInfoList
	2, // 5: protobuf.ContactResolver.GetContactInfo:output_type -> protobuf.ContactInfo
	0, // 6: protobuf.ContactResolver.DeleteContact:output_type -> protobuf.Empty
	0, // 7: protobuf.ContactResolver.AddContact:output_type -> protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ContactResolver_proto_init() }
func file_proto_ContactResolver_proto_init() {
	if File_proto_ContactResolver_proto != nil {
		return
	}
	file_proto_Message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ContactResolver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ContactResolver_proto_goTypes,
		DependencyIndexes: file_proto_ContactResolver_proto_depIdxs,
	}.Build()
	File_proto_ContactResolver_proto = out.File
	file_proto_ContactResolver_proto_rawDesc = nil
	file_proto_ContactResolver_proto_goTypes = nil
	file_proto_ContactResolver_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ContactResolverClient is the client API for ContactResolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactResolverClient interface {
	GetAllContactInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ContactMetaInfoList, error)
	GetContactInfo(ctx context.Context, in *String, opts ...grpc.CallOption) (*ContactInfo, error)
	DeleteContact(ctx context.Context, in *String, opts ...grpc.CallOption) (*Empty, error)
	AddContact(ctx context.Context, in *ContactInfo, opts ...grpc.CallOption) (*Empty, error)
}

type contactResolverClient struct {
	cc grpc.ClientConnInterface
}

func NewContactResolverClient(cc grpc.ClientConnInterface) ContactResolverClient {
	return &contactResolverClient{cc}
}

func (c *contactResolverClient) GetAllContactInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ContactMetaInfoList, error) {
	out := new(ContactMetaInfoList)
	err := c.cc.Invoke(ctx, "/protobuf.ContactResolver/GetAllContactInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactResolverClient) GetContactInfo(ctx context.Context, in *String, opts ...grpc.CallOption) (*ContactInfo, error) {
	out := new(ContactInfo)
	err := c.cc.Invoke(ctx, "/protobuf.ContactResolver/GetContactInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactResolverClient) DeleteContact(ctx context.Context, in *String, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protobuf.ContactResolver/DeleteContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactResolverClient) AddContact(ctx context.Context, in *ContactInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protobuf.ContactResolver/AddContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactResolverServer is the server API for ContactResolver service.
type ContactResolverServer interface {
	GetAllContactInfo(context.Context, *Empty) (*ContactMetaInfoList, error)
	GetContactInfo(context.Context, *String) (*ContactInfo, error)
	DeleteContact(context.Context, *String) (*Empty, error)
	AddContact(context.Context, *ContactInfo) (*Empty, error)
}

// UnimplementedContactResolverServer can be embedded to have forward compatible implementations.
type UnimplementedContactResolverServer struct {
}

func (*UnimplementedContactResolverServer) GetAllContactInfo(context.Context, *Empty) (*ContactMetaInfoList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllContactInfo not implemented")
}
func (*UnimplementedContactResolverServer) GetContactInfo(context.Context, *String) (*ContactInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContactInfo not implemented")
}
func (*UnimplementedContactResolverServer) DeleteContact(context.Context, *String) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContact not implemented")
}
func (*UnimplementedContactResolverServer) AddContact(context.Context, *ContactInfo) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddContact not implemented")
}

func RegisterContactResolverServer(s *grpc.Server, srv ContactResolverServer) {
	s.RegisterService(&_ContactResolver_serviceDesc, srv)
}

func _ContactResolver_GetAllContactInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactResolverServer).GetAllContactInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ContactResolver/GetAllContactInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactResolverServer).GetAllContactInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactResolver_GetContactInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactResolverServer).GetContactInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ContactResolver/GetContactInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactResolverServer).GetContactInfo(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactResolver_DeleteContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactResolverServer).DeleteContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ContactResolver/DeleteContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactResolverServer).DeleteContact(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactResolver_AddContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContactInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactResolverServer).AddContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ContactResolver/AddContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactResolverServer).AddContact(ctx, req.(*ContactInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContactResolver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.ContactResolver",
	HandlerType: (*ContactResolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllContactInfo",
			Handler:    _ContactResolver_GetAllContactInfo_Handler,
		},
		{
			MethodName: "GetContactInfo",
			Handler:    _ContactResolver_GetContactInfo_Handler,
		},
		{
			MethodName: "DeleteContact",
			Handler:    _ContactResolver_DeleteContact_Handler,
		},
		{
			MethodName: "AddContact",
			Handler:    _ContactResolver_AddContact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ContactResolver.proto",
}
