// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: proto/PhoneResolver.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_PhoneResolver_proto protoreflect.FileDescriptor

var file_proto_PhoneResolver_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x73, 0x0a, 0x0d, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x09, 0x44,
	0x69, 0x61, 0x6c, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x30, 0x0a,
	0x09, 0x43, 0x61, 0x6c, 0x6c, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42,
	0x43, 0x0a, 0x1f, 0x63, 0x6f, 0x6d, 0x2e, 0x6a, 0x6f, 0x78, 0x72, 0x61, 0x79, 0x73, 0x2e, 0x67,
	0x6f, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x73, 0x76, 0x72, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x72, 0x42, 0x12, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x01, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_proto_PhoneResolver_proto_goTypes = []interface{}{
	(*String)(nil), // 0: protobuf.String
	(*Empty)(nil),  // 1: protobuf.Empty
}
var file_proto_PhoneResolver_proto_depIdxs = []int32{
	0, // 0: protobuf.PhoneResolver.DialPhone:input_type -> protobuf.String
	0, // 1: protobuf.PhoneResolver.CallPhone:input_type -> protobuf.String
	1, // 2: protobuf.PhoneResolver.DialPhone:output_type -> protobuf.Empty
	1, // 3: protobuf.PhoneResolver.CallPhone:output_type -> protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_PhoneResolver_proto_init() }
func file_proto_PhoneResolver_proto_init() {
	if File_proto_PhoneResolver_proto != nil {
		return
	}
	file_proto_Message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_PhoneResolver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_PhoneResolver_proto_goTypes,
		DependencyIndexes: file_proto_PhoneResolver_proto_depIdxs,
	}.Build()
	File_proto_PhoneResolver_proto = out.File
	file_proto_PhoneResolver_proto_rawDesc = nil
	file_proto_PhoneResolver_proto_goTypes = nil
	file_proto_PhoneResolver_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PhoneResolverClient is the client API for PhoneResolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PhoneResolverClient interface {
	DialPhone(ctx context.Context, in *String, opts ...grpc.CallOption) (*Empty, error)
	CallPhone(ctx context.Context, in *String, opts ...grpc.CallOption) (*Empty, error)
}

type phoneResolverClient struct {
	cc grpc.ClientConnInterface
}

func NewPhoneResolverClient(cc grpc.ClientConnInterface) PhoneResolverClient {
	return &phoneResolverClient{cc}
}

func (c *phoneResolverClient) DialPhone(ctx context.Context, in *String, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protobuf.PhoneResolver/DialPhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneResolverClient) CallPhone(ctx context.Context, in *String, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protobuf.PhoneResolver/CallPhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhoneResolverServer is the server API for PhoneResolver service.
type PhoneResolverServer interface {
	DialPhone(context.Context, *String) (*Empty, error)
	CallPhone(context.Context, *String) (*Empty, error)
}

// UnimplementedPhoneResolverServer can be embedded to have forward compatible implementations.
type UnimplementedPhoneResolverServer struct {
}

func (*UnimplementedPhoneResolverServer) DialPhone(context.Context, *String) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DialPhone not implemented")
}
func (*UnimplementedPhoneResolverServer) CallPhone(context.Context, *String) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallPhone not implemented")
}

func RegisterPhoneResolverServer(s *grpc.Server, srv PhoneResolverServer) {
	s.RegisterService(&_PhoneResolver_serviceDesc, srv)
}

func _PhoneResolver_DialPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneResolverServer).DialPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.PhoneResolver/DialPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneResolverServer).DialPhone(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhoneResolver_CallPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneResolverServer).CallPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.PhoneResolver/CallPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneResolverServer).CallPhone(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

var _PhoneResolver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.PhoneResolver",
	HandlerType: (*PhoneResolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DialPhone",
			Handler:    _PhoneResolver_DialPhone_Handler,
		},
		{
			MethodName: "CallPhone",
			Handler:    _PhoneResolver_CallPhone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/PhoneResolver.proto",
}
