// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PingTestClient is the client API for PingTest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingTestClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type pingTestClient struct {
	cc grpc.ClientConnInterface
}

func NewPingTestClient(cc grpc.ClientConnInterface) PingTestClient {
	return &pingTestClient{cc}
}

func (c *pingTestClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protobuf.PingTest/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingTestServer is the server API for PingTest service.
// All implementations must embed UnimplementedPingTestServer
// for forward compatibility
type PingTestServer interface {
	Ping(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedPingTestServer()
}

// UnimplementedPingTestServer must be embedded to have forward compatible implementations.
type UnimplementedPingTestServer struct {
}

func (UnimplementedPingTestServer) Ping(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPingTestServer) mustEmbedUnimplementedPingTestServer() {}

// UnsafePingTestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingTestServer will
// result in compilation errors.
type UnsafePingTestServer interface {
	mustEmbedUnimplementedPingTestServer()
}

func RegisterPingTestServer(s grpc.ServiceRegistrar, srv PingTestServer) {
	s.RegisterService(&PingTest_ServiceDesc, srv)
}

func _PingTest_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingTestServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.PingTest/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingTestServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PingTest_ServiceDesc is the grpc.ServiceDesc for PingTest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingTest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.PingTest",
	HandlerType: (*PingTestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PingTest_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/Ping.proto",
}
